export { api, qs, type Paged, type Query } from './client';
export { API_URL, API_V1 } from './config';
export { ApiError, useApiErrorMessage, type ApiErrorCode, type ValidationIssue } from './errors';
export { qk } from './query-keys';
export * from './types';
export { useProfile, useUpdateProfile } from './profile';
export { useHome, useCategories, useBrands, useLensAddons, useBanners } from './catalog';
export { useProducts, useProduct, useProductReviews } from './products';
export { useCart, type CartApi } from './cart';
export { useWishlist, useWishlistProducts } from './wishlist';
export { usePrescriptions, useCreatePrescription, useDeletePrescription } from './prescriptions';
export { useOrders, useOrder, useCheckout, useCancelOrder } from './orders';
export { useAddresses, useCreateAddress, useUpdateAddress, useSetDefaultAddress, useDeleteAddress } from './addresses';
export { useDoctors, useAvailability, useAppointments, useBookAppointment, useCancelAppointment, useRescheduleAppointment, type AvailabilityParams } from './appointments';
export { useNotifications, useMarkNotificationsRead, registerDevice, unregisterDevice } from './notifications';
